# Generated by Django 4.0.1 on 2022-03-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveIntegerField(choices=[(1, 'trainee'), (2, 'probation'), (3, 'junior'), (4, 'middle-'), (5, 'middle'), (6, 'middle+'), (7, 'senior')], null=True)),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('daily_hours', models.PositiveIntegerField()),
                ('hire_date', models.DateField()),
                ('dismiss_date', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
    ]
