# Generated by Django 4.0.1 on 2022-03-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_choco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chocolate',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
