# Generated by Django 4.0.1 on 2022-03-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('store_info', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('is_photo_needed', models.BooleanField(default=False)),
            ],
        ),
    ]
